//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ApplicationInfo
{
    public int id { get; set; }
    public string name { get; set; }
    public int gender { get; set; }
    public string department { get; set; }
    public string rank { get; set; }
    public string message { get; set; }
    public string submit_time { get; set; }
}

public partial class JudgeApplication
{
    public int id { get; set; }
    public int teacher_id { get; set; }
    public string message { get; set; }
    public string submit_time { get; set; }

    public virtual Teacher Teacher { get; set; }
}

public partial class Project
{
    public Project()
    {
        this.ProjectJudge = new HashSet<ProjectJudge>();
        this.ProjectStage = new HashSet<ProjectStage>();
    }

    public int project_id { get; set; }
    public string name { get; set; }
    public int category { get; set; }
    public int teacher_id { get; set; }
    public string submit_time { get; set; }

    public virtual ProjectCategory ProjectCategory { get; set; }
    public virtual Teacher Teacher { get; set; }
    public virtual ICollection<ProjectJudge> ProjectJudge { get; set; }
    public virtual ICollection<ProjectStage> ProjectStage { get; set; }
}

public partial class ProjectCategory
{
    public ProjectCategory()
    {
        this.Project = new HashSet<Project>();
    }

    public int id { get; set; }
    public string name { get; set; }
    public string project_content { get; set; }
    public int stage { get; set; }
    public string end_time { get; set; }
    public string project_file { get; set; }
    public string judge_end_time { get; set; }

    public virtual ICollection<Project> Project { get; set; }
}

public partial class ProjectInfo
{
    public int project_id { get; set; }
    public string name { get; set; }
    public string category_name { get; set; }
    public string teacher_name { get; set; }
    public string submit_time { get; set; }
    public int category { get; set; }
}

public partial class ProjectJudge
{
    public int id { get; set; }
    public int project_id { get; set; }
    public int category { get; set; }
    public int teacher_id { get; set; }
    public int judge_id { get; set; }
    public string judge_name { get; set; }
    public int stage { get; set; }
    public string comment { get; set; }
    public int is_pass { get; set; }

    public virtual Project Project { get; set; }
}

public partial class ProjectStage
{
    public int id { get; set; }
    public int project_id { get; set; }
    public string project_content { get; set; }
    public int stage { get; set; }
    public string time { get; set; }
    public int is_pass { get; set; }
    public string project_file { get; set; }

    public virtual Project Project { get; set; }
}

public partial class Teacher
{
    public Teacher()
    {
        this.Project = new HashSet<Project>();
        this.JudgeApplication = new HashSet<JudgeApplication>();
    }

    public int id { get; set; }
    public string name { get; set; }
    public string password { get; set; }
    public string image { get; set; }
    public int gender { get; set; }
    public string email { get; set; }
    public string number { get; set; }
    public string phone_number { get; set; }
    public string department { get; set; }
    public string rank { get; set; }
    public int is_judge { get; set; }

    public virtual ICollection<Project> Project { get; set; }
    public virtual ICollection<JudgeApplication> JudgeApplication { get; set; }
}
