//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class TeachingCenterEntities : DbContext
{
    public TeachingCenterEntities()
        : base("name=TeachingCenterEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<Project> Project { get; set; }
    public DbSet<ProjectCategory> ProjectCategory { get; set; }
    public DbSet<ProjectJudge> ProjectJudge { get; set; }
    public DbSet<ProjectStage> ProjectStage { get; set; }
    public DbSet<Teacher> Teacher { get; set; }
    public DbSet<ProjectInfo> ProjectInfo { get; set; }
    public DbSet<ApplicationInfo> ApplicationInfo { get; set; }
    public DbSet<JudgeApplication> JudgeApplication { get; set; }
}
