//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Admin
{
    public string Admin_id { get; set; }
    public string Admin_pwd { get; set; }
    public string Admin_name { get; set; }
}

public partial class Develop
{
    public int Develop_id { get; set; }
    public string Develop_title { get; set; }
    public string Develop_author { get; set; }
    public System.DateTime Develop_time { get; set; }
    public string Develop_content { get; set; }
    public string Develop_link { get; set; }
    public int Develop_hit { get; set; }
    public long Develop_deleted { get; set; }
}

public partial class Introduction
{
    public int Introduction_id { get; set; }
    public string Introduction_content { get; set; }
}

public partial class Picture
{
    public int Picture_id { get; set; }
    public string Picture_path { get; set; }
}
